In [1]:
import pandas as pd
import numpy as np
import yaml
import pypdf
# import requests
# from bs4 import BeautifulSoup

In [5]:
import os
ext = os.path.splitext(config['input_data']['economical'])[1]

engine = "xlrd" if ext == ".xls" else "openpyxl"

poverty = pd.read_excel(
    config['input_data']['economical'],
    sheet_name="Armut",
    engine=engine
)

In [6]:

try:
    with open("../config.yaml", "r") as file:
        config = yaml.safe_load(file)
except FileNotFoundError:
    print("Yaml configuration file not found!")

# Read the 'armut' sheet from the Excel file defined in config.yaml
poverty = pd.read_excel(
    config['input_data']['economical'],  # path from your YAML config
    sheet_name="Armut",                  # specify the sheet
    engine="openpyxl"                    # for .xlsx files
)

print(poverty.head())

  A1a I Armutsgefährdungsquoten der Bevölkerung1 2005 bis 2024 nach Berliner Bezirken und \n           Brandenburger Kreisen und kreisfreien Städten  \
0                         Ergebnisse des Mikrozensus
1                                                NaN
2                                             Region
3                                                NaN
4                                                NaN

  Unnamed: 1 Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
0        NaN        NaN         NaN         NaN         NaN         NaN
1        NaN        NaN         NaN         NaN         NaN         NaN
2        NaN       2005      2006.0      2007.0      2008.0      2009.0
3        NaN          %         NaN         NaN         NaN         NaN
4        NaN        NaN         NaN         NaN         NaN         NaN

   Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 12  Unnamed: 13  \
0         NaN         NaN         NaN  ...          NaN          NaN
1         NaN         NaN         NaN  ...          NaN          NaN
2      2010.0      2011.0      2012.0  ...       2015.0       2016.0
3         NaN         NaN         NaN  ...          NaN          NaN
4         NaN         NaN         NaN  ...          NaN          NaN

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2       2017.0       2018.0       2019.0       2020 1        2021²
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

  Unnamed: 19 Unnamed: 20  Unnamed: 21
0         NaN         NaN          NaN
1         NaN         NaN          NaN
2      2022.0      2023.0        2024³
3         NaN         NaN          NaN
4         NaN         NaN          NaN

[5 rows x 22 columns]

In [8]:
poverty

,A1a I Armutsgefährdungsquoten der Bevölkerung1 2005 bis 2024 nach Berliner Bezirken und \n Brandenburger Kreisen und kreisfreien Städten,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Ergebnisse des Mikrozensus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Region,NaN,2005,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,...,2015.0,2016.0,2017.0,2018.0,2019.0,2020 1,2021²,2022.0,2023.0,2024³
3,NaN,NaN,%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,im Landesmaßstab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Berlin,NaN,16.1,13.3,13.9,14.3,14.1,14.2,15.5,15.2,...,15.3,16.6,17.4,16.5,17.8,19,19.6,18.5,19.7,19.1
7,NaN,Mitte,23.1,20.2,21.6,21.7,23.1,18.6,22.2,19.1,...,20.4,24.8,25.6,20.2,23.3,x,27.2,23.2,23.7,24
8,NaN,Friedrichshain-Kreuzberg,21.8,18.5,21.5,22.8,21.1,21.3,20.6,20.9,...,17.4,19.7,18.0,17.0,19.8,x,19.3,17.8,19.0,21
9,NaN,Pankow,13,9.2,10.0,11.9,9.6,10.4,11.1,10.2,...,8.9,6.4,6.8,6.7,8.4,x,12.1,11.8,12.6,14.4
10,NaN,Charlottenburg-Wilmersdorf,16.1,12.0,13.9,12.5,12.1,12.2,14.5,14.1,...,14.7,15.4,17.4,15.7,16.1,x,17.1,14.0,17.7,18.1
11,NaN,Spandau,15.7,13.7,14.4,12.0,14.5,16.2,17.1,17.3,...,18.4,23.2,24.1,24.3,23.6,x,22.4,20.9,19.2,20
12,NaN,Steglitz-Zehlendorf,10.3,6.2,5.3,5.2,7.6,8.6,9.4,9.0,...,8.4,10.5,11.1,11.1,10.2,x,15.5,15.8,14.3,13.7
13,NaN,Tempelhof-Schöneberg,16.3,12.6,13.9,15.8,12.2,12.4,14.0,14.0,...,15.8,17.7,17.4,15.6,16.6,x,20.5,17.9,21.4,17.7
14,NaN,Neukölln,21.8,19.8,17.3,20.3,21.1,22.5,23.5,24.0,...,25.3,26.8,26.2,27.4,29.2,x,31.4,30.4,26.3,24.4
15,NaN,Treptow-Köpenick,9.2,8.6,8.7,8.0,9.4,10.0,9.3,11.8,...,9.2,10.5,12.7,11.3,12.2,x,12.7,14.2,16.6,14.4
16,NaN,Marzahn-Hellersdorf,14,13.9,14.0,16.6,15.6,15.6,16.0,15.4,...,15.7,16.5,17.3,16.8,18.1,x,17.8,19.6,19.6,16.8
17,NaN,Lichtenberg,16.4,13.8,11.9,11.9,11.1,11.9,14.5,12.5,...,15.6,14.4,17.3,18.1,19.9,x,18.1,19.6,26.2,25.2
18,NaN,Reinickendorf,13.3,10.0,12.2,10.4,11.3,12.5,12.4,14.7,...,13.6,15.5,15.5,16.9,19.0,x,21.6,18.8,21.8,20.7
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,_____,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1 Die Ergebnisse des Mikrozensus ab dem Erhebu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2 ab 2021 Hochrechnung nach Fortschreibung/Rüc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3 Erstergebnis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#chart > div > div.map-outer > svg > g > path